### ISSUE TITLE
Sistema básico de autenticação e autorização

### ISSUE THREAD

**Issue by Arthurpmrs** [BeaRoodriguees/lovelace#1]
Para o Frontend: https://next-auth.js.org/
Para o backend: 
- https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/
- https://fastapidozero.dunossauro.com/06/

## To-do
- [x] (Backend) Implementar modelo do usuário
- [x] (Backend) Implementar geração de token
- [x] (Frontend) Configurar NextAuth
- [x] (Frontend) Criar tela de registro (e modificar backend conforme necessário)
- [x] (Frontend) Criar tela de Login (e modificar backend conforme necessário)
- [x] (Backend) Implementar Roles (**User**, **Admin**)
- [x] (Frontend) Gerenciar rotas permitidas por role
- [x] (Backend) Add endpoint unit tests
